# Generated by Django 5.0.1 on 2025-03-14 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(unique=True)),
                ('is_default', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SchoolNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('extra_effort', models.TextField(blank=True)),
                ('areas_for_improvement', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('family_teachers', models.ManyToManyField(blank=True, related_name='managed_homes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), ('H', 'Hallway')], max_length=2)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.schoolnote')),
            ],
        ),
        migrations.CreateModel(
            name='BehaviorEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_positive', models.BooleanField()),
                ('notes', models.TextField(blank=True)),
                ('behavior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notes.behavior')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.period')),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('teacher_acknowledgement', models.TextField(blank=True)),
                ('school_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.schoolnote')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notes.home')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='schoolnote',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.student'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolnote',
            unique_together={('student', 'date')},
        ),
    ]
